language: python
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.5
- 3.6
- pypy3

os:
- linux

install:
- pip install -e .[tests]
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* && $TRAVIS_OS_NAME == linux  ]]; then pip install -e .[cov]; fi

script:
- pytest -rsv
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* && $TRAVIS_OS_NAME == linux  ]]; then flake8; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* && $TRAVIS_OS_NAME == linux  ]]; then mypy . --ignore-missing-imports; fi

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.6* && $TRAVIS_OS_NAME == linux ]]; then
  pytest --cov --cov-config=setup.cfg;
  coveralls;
  fi

