language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

git:
  depth: 3


install: pip -q install -e .[tests]

script:
  - pytest -v
  - mypy . --ignore-missing-imports
  - flake8

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then 
    coverage run tests/test_all.py;
    coveralls; 
    fi
